qpsolvers/qpsolvers

examples/dense_problem.py
examples/random_problems.py
examples/simple_example.py
examples/sparse_problem.py
qpsolvers/cvxpy_.py
qpsolvers/gurobi_.py
qpsolvers/mosek_.py
qpsolvers/osqp_.py
qpsolvers/qpoases_.py
qpsolvers/quadprog_.py

Love the package, really. I don't understand why all the convex solvers out there have such fucked up interfaces. Not only do you streamline them, you even allow for sparsity where possible.
This is just a minor Python 3 compatibility fix that hopefully will help new users of your package realize its awesomeness directly.

Python3 compatibility

---

qpsolvers/gurobi_.py

Updating the Gurobi QP interface with the matrix API. It should work with dense and sparse arrays, except for the linear term in the objective function.

Gurobi 9.0 patch

---

CHANGELOG.md
qpsolvers/solvers/osqp_.py

See https://github.com/stephane-caron/qpsolvers/issues/59

OSQP: Pass extra keyword arguments properly

---

tox.ini

As https://github.com/Simple-Robotics/proxsuite/issues/113 has been fixed

Fix minimal version for proxsuite

---

CHANGELOG.md
doc/src/developer-notes.rst
qpsolvers/__init__.py
qpsolvers/conversions/split_dual_linear_box.py
qpsolvers/solution.py
qpsolvers/solvers/cvxopt_.py
qpsolvers/solvers/ecos_.py
qpsolvers/solvers/qpswift_.py
qpsolvers/solvers/quadprog_.py
tests/solved_problems.py
tests/test_conversions.py
tests/test_dual.py
tox.ini

This PR closes https://github.com/stephane-caron/qpsolvers/issues/135

Fix duality gap computation for infinite box bounds

---

CHANGELOG.md
qpsolvers/__init__.py
qpsolvers/conversions/linear_from_box_inequalities.py
qpsolvers/exceptions.py
qpsolvers/problem.py
qpsolvers/solvers/cvxopt_.py
qpsolvers/solvers/ecos_.py
qpsolvers/solvers/qpoases_.py
qpsolvers/solvers/qpswift_.py
qpsolvers/solvers/quadprog_.py
tests/test_conversions.py
tests/test_problem.py
tests/test_qpoases.py
tests/test_qpswift.py
tests/test_quadprog.py

Closes https://github.com/stephane-caron/qpsolvers/issues/140

Sparse box inequality conversions

---

CHANGELOG.md
doc/src/installation.rst
qpsolvers/solvers/qpoases_.py

Closes https://github.com/stephane-caron/qpsolvers/issues/151

Fix qpOASES segmentation fault

---

CHANGELOG.md
qpsolvers/solvers/qpoases_.py
tests/solved_problems.py
tests/test_solve_problem.py
tests/test_solve_qp.py

Closes https://github.com/stephane-caron/qpsolvers/issues/113

Fix qpOASES infinity bounds

---

CHANGELOG.md
qpsolvers/conversions/socp_from_qp.py
qpsolvers/problem.py
tests/solved_problems.py
tests/test_problem.py
tests/test_solve_problem.py

Fixes https://github.com/stephane-caron/qpsolvers/issues/165

Check problem vector shapes

---

tests/solved_problems.py
tests/test_problem.py
tests/test_solve_problem.py

This case warrants checking the cost matrix dimensions when building a problem.

Add unit test for unidimensional QP

---

CHANGELOG.md
qpsolvers/solvers/__init__.py
qpsolvers/solvers/clarabel_.py
tests/test_clarabel.py
tests/test_conversions.py
tests/test_cvxopt.py
tests/test_ecos.py
tests/test_gurobi.py
tests/test_highs.py
tests/test_mosek.py
tests/test_osqp.py
tests/test_problem.py
tests/test_proxqp.py
tests/test_qpoases.py
tests/test_qpswift.py
tests/test_quadprog.py
tests/test_scs.py
tests/test_solution.py
tests/test_solve_ls.py
tests/test_solve_problem.py
tests/test_solve_qp.py
tests/test_unfeasible_problem.py
tests/test_utils.py

Closes https://github.com/stephane-caron/qpsolvers/issues/173

Add Clarabel solver

---

CHANGELOG.md
pyproject.toml

Closes https://github.com/qpsolvers/qpsolvers/issues/189

Only depend on solvers with arm64 wheels

---

pyproject.toml
tests/test_solve_problem.py
tox.ini

Follows the release of https://github.com/oxfordcontrol/Clarabel.rs/releases/tag/v0.4.1
Follow up to https://github.com/oxfordcontrol/Clarabel.rs/issues/14

Update Clarabel version to 0.4.1

---

CHANGELOG.md
README.md
examples/sparse_least_squares.py
qpsolvers/problems.py
qpsolvers/solve_ls.py
qpsolvers/solvers/cvxopt_.py
tests/problems.py
tests/test_solve_ls.py

Closes https://github.com/qpsolvers/qpsolvers/issues/192

Solve LS alternative conversion for sparse problems

---

.github/workflows/docs.yml
README.md
doc/references.rst
doc/supported-solvers.rst
pyproject.toml
qpsolvers/__init__.py
qpsolvers/solvers/__init__.py
qpsolvers/solvers/daqp_.py
tox.ini

This PR adds the dual active-set solver [DAQP](https://darnstrom.github.io/daqp/), which is aimed towards solving dense positive-definite QPs.

Add interface to DAQP

---

pyproject.toml
tox.ini

See https://github.com/qpsolvers/qpsolvers/issues/204

Update DAQP to 0.5.1

---

CHANGELOG.md
qpsolvers/solvers/mosek_.py
tests/test_solve_ls.py

@aszekMosek thanks for your feedback in https://github.com/qpsolvers/qpsolvers/issues/213#issuecomment-1527051006. Addressing it in this PR.

Fix MOSEK interface and test problem

---

CHANGELOG.md
qpsolvers/solvers/ecos_.py
tests/test_ecos.py
tests/test_solve_problem.py

Closes https://github.com/stephane-caron/qpsolvers/issues/160

ECOS: detect infinite inequality values

---

CHANGELOG.md
qpsolvers/__init__.py
qpsolvers/active_set.py
qpsolvers/problem.py
tests/test_problem.py

Closes https://github.com/qpsolvers/qpsolvers/issues/220

Condition number with active set

---

.github/workflows/test.yml
tox.ini

To ease checks in external contributions

Only test MOSEK in coverage tests

---

.github/workflows/test.yml

See https://stackoverflow.com/a/70249520

Check that secrets are defined in CI when needed

---

CHANGELOG.md
examples/lasso_regularization.py

See https://github.com/qpsolvers/qpsolvers/discussions/223#discussioncomment-7873692

Add lasso regularization example

---

CHANGELOG.md
qpsolvers/solve_ls.py
qpsolvers/solve_qp.py

Closes https://github.com/qpsolvers/qpsolvers/issues/276

[docs] Correct note in solve_ls documentation

---

CHANGELOG.md
doc/least-squares.rst

Closes https://github.com/qpsolvers/qpsolvers/issues/278

Fix least-squares example

---

CHANGELOG.md
qpsolvers/solvers/qpalm_.py
tests/test_solve_qp.py

Closes https://github.com/qpsolvers/qpsolvers/issues/287

Specify solver tolerance in sparse test

---

CHANGELOG.md
README.md
pyproject.toml

Closes https://github.com/qpsolvers/qpsolvers/issues/291

Add wheels_only optional dependency

---

CHANGELOG.md
CITATION.cff
README.md
pyproject.toml
qpsolvers/__init__.py

See https://github.com/qpsolvers/qpsolvers/issues/296

Solvers need aarch64-macOS wheels to be in wheels_only

---

CHANGELOG.md
qpsolvers/solvers/clarabel_.py

See https://github.com/oxfordcontrol/Clarabel.rs/issues/127
See also https://github.com/PyO3/pyo3/issues/2880

Clarabel: Catch pyO3 panics exns when building a problem

---

CHANGELOG.md
CITATION.cff
README.md
qpsolvers/__init__.py

This release adds [KVXOPT](https://github.com/sanurielf/kvxopt), a fork from CVXOPT including more SuiteSparse functions and KLU sparse matrix solver. Thanks to @agroudiev for implementing this interface 👍
Additionally, this new version extends support to JAX arrays when using the jaxopt.OSQP solver.
- New solver: [KVXOPT](https://github.com/sanurielf/kvxopt/)
- jaxopt.OSQP: Support JAX array inputs when jaxopt.OSQP is the selected solver

Release v4.6.0

---

CHANGELOG.md
README.md
doc/environment.yml
doc/supported-solvers.rst
pyproject.toml
qpsolvers/__init__.py
qpsolvers/solvers/__init__.py
qpsolvers/solvers/sip_.py
tests/test_sip.py
tests/test_solve_ls.py
tests/test_solve_problem.py
tests/test_solve_qp.py
tox.ini

This PR adds support for SIP, a C++ NLP solver.
Relevant links:
C++ Solver: https://github.com/joaospinto/sip
Python bindings: https://github.com/joaospinto/sip_python

Add support for sip_python.
