qpsolvers/quadprog_.py
If A is a 1-dim array, e.g. created with `numpy.array([1., 2.])`, the result of `quadprog_solve_qp` is wrong because the `meq` is calculated incorrectly as `meq = A.shape[0]`. I suggest using something like `A.shape[0] if A.ndim > 1 else 1` instead.
=> Fix quadprog wrapper for 1-dim A matrix

qpsolvers/quadprog_.py
Hi,
This is a fix when G or h are None with quadprog.
Best,
Brian
=> fix quadprog when G, h constraints are None

README.md
The site on <https://projects.coin-or.org/qpOASES> says "This project has moved to <​https://github.com/coin-or/qpOASES>", so I updated the URL.
=> [minor] Update a link to qpOASES

qpsolvers/quadprog_.py
-  As reported in this issue https://github.com/stephane-caron/qpsolvers/issues/25 
- When a value error occurs (for example a mix of value types) then an error is raised within raising the value error because it is searching for a string in an object rather than in the error message itself.
=> Fix for searching in error object rather than message string

qpsolvers/cvxpy_.py
The deprecation warning was the following:
```
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
Use ``*`` for matrix-scalar and vector-scalar multiplication.
Use ``@`` for matrix-matrix and matrix-vector multiplication.
Use ``multiply`` for elementwise multiplication.
```
=> [cvxpy] fix deprecation warning

qpsolvers/quadprog_.py
quadprog_solve_qp raises a value error if you give an infeasible problem. This is not what the docs say the behavior is. The behavior should be returns ```None``` if we have an infeasible problem.
=> Fixing quadprog_solve_qp behavior with infeasible problems

CHANGELOG.md, README.md, examples/benchmark_random_problems.py, pyproject.toml, qpsolvers/solvers/__init__.py, qpsolvers/solvers/cvxopt_.py, qpsolvers/solvers/cvxpy_.py, qpsolvers/solvers/ecos_.py, qpsolvers/solvers/gurobi_.py, qpsolvers/solvers/mosek_.py, qpsolvers/solvers/osqp_.py, qpsolvers/solvers/qpoases_.py, qpsolvers/solvers/quadprog_.py, qpsolvers/solvers/scs_.py, qpsolvers/solvers/typing.py, tests/test_solve_qp.py, tox.ini
Discussion at bodono/scs-python#36.
=> Update to SCS 3.0

CHANGELOG.md, qpsolvers/__init__.py, qpsolvers/conversions/linear_from_box_inequalities.py, qpsolvers/conversions/socp_from_qp.py, qpsolvers/exceptions.py, qpsolvers/problem.py, qpsolvers/solve_qp.py, qpsolvers/solvers/cvxopt_.py, qpsolvers/solvers/proxqp_.py, qpsolvers/solvers/qpoases_.py, qpsolvers/solvers/quadprog_.py, qpsolvers/solvers/scs_.py, tests/test_cvxopt.py, tests/test_problem.py, tests/test_proxqp.py, tests/test_quadprog.py, tests/test_scs.py, tests/test_solve_qp.py
We catch all solver exceptions and re-throw them in a qpsolvers-owned exception to avoid abstraction leakage. See this [design decision](https://github.com/getparthenon/parthenon/wiki/Design-Decision:-Throw-Custom-Exceptions) for more details on the rationale behind this choice.
=> [v3] Only throw qpsolvers-owned exceptions

CHANGELOG.md, qpsolvers/solution.py, qpsolvers/solve_qp.py, qpsolvers/solvers/cvxopt_.py, qpsolvers/solvers/ecos_.py, qpsolvers/solvers/gurobi_.py, qpsolvers/solvers/highs_.py, qpsolvers/solvers/mosek_.py, qpsolvers/solvers/osqp_.py, qpsolvers/solvers/proxqp_.py, qpsolvers/solvers/qpoases_.py, qpsolvers/solvers/qpswift_.py, qpsolvers/solvers/quadprog_.py, qpsolvers/solvers/scs_.py, tests/test_solution.py, tests/test_unfeasible_problem.py
This PR adds a ``Solution.found`` attribute.
Previously, ``Solution.x`` being ``None`` was used to check whether the solver found a solution or not. The drawback of that choice was that some solvers return primal solutions ``x`` even when they don't identify an optimum (for instance when a maximum number of iterations is reached), and this information was lost.
With this new attribute, we can save any value in ``Solution.x`` while the existence is now checked in ``Solution.found``.
=> [v3] Add found attribute to Solution

CHANGELOG.md, CITATION.cff, README.md, doc/installation.rst, pyproject.toml, qpsolvers/__init__.py
Enable installing a subset of QP solvers, for instance:
```console
pip install qpsolvers[clarabel,daqp,proxqp,scs]
```
Suggested by @sandeep026 in https://github.com/qpsolvers/qpsolvers/discussions/247
=> Update optional deps to install specific solvers

README.md, qpsolvers/solvers/__init__.py
Similarly to OSQP, QPALM's API requires sparse matrices and we issue a warning if dense matrices are provided. This is what defines the difference between `dense_solvers` and `sparse_solvers`.
=> Mark QPALM as a sparse solver only

qpsolvers/unsupported/nppro_.py
In the recent development of the NPPro solver, the exitflag value for successful solution has been changed. Previously, the successful solution was 0, currently, the successful solution is 1.
This PR is fixing the check in the solver integration.
=> [nppro] Changed exitflag value in solution check

CHANGELOG.md, doc/environment.yml, doc/supported-solvers.rst
That was missing from https://github.com/qpsolvers/qpsolvers/pull/175
Closes https://github.com/qpsolvers/qpsolvers/issues/270
=> Add Clarabel to the list of supported solvers in the docs

qpsolvers/solvers/piqp_.py
Running ```ipython -i test_model_predictive_control.py``` generates a warning message to convert from np.ndarray to csc_matrix: "ensure_sparse_matrices.py:24: UserWarning: Converted A to scipy.sparse.csc.csc_matrix
For best performance, build A as a scipy.sparse.csc_matrix rather than as a numpy.ndarray
warnings.warn(". 
Original code: 
```python
G_piqp = np.zeros((0, n)) if G is None else G
h_piqp = np.zeros((0,)) if h is None else h
A_piqp = np.zeros((0, n)) if A is None else A
b_piqp = np.zeros((0,)) if b is None else b
use_csc: bool = (
not isinstance(P, np.ndarray)
or (G is not None and not isinstance(G, np.ndarray))
or (A is not None and not isinstance(A, np.ndarray))
)
```
Changed code: 
```python 
use_csc: bool = (
not isinstance(P, np.ndarray)
or (G is not None and not …
```
=> warning message csc_matrix for piqp when A is None

.github/workflows/ci.yml, CHANGELOG.md, pyproject.toml, qpsolvers/solution.py, tox.ini
- Add support for Python 3.12
- Bump minimum Python version to 3.8
See also: [Status of Python versions](https://devguide.python.org/versions/).
Closes https://github.com/qpsolvers/qpsolvers/discussions/312
=> Add support for Python 3.12

.github/workflows/ci.yml, CHANGELOG.md, pyproject.toml, tox.ini
Python 3.8 has reached its end of life: https://devguide.python.org/versions/
=> Remove Python 3.8 from continuous integration

CHANGELOG.md, CITATION.cff, README.md, qpsolvers/__init__.py, qpsolvers/solvers/osqp_.py
This patch release adds a workaround to handle OSQP infeasibility certificates with both pre-1.0 and 1.0.3 versions of the solver.
- CICD: Update checkout action to v4
- OSQP: Temporary fix in returning primal-dual infeasibility certificates
=> Release v4.5.1

CHANGELOG.md, README.md, doc/environment.yml, qpsolvers/_internals.py, qpsolvers/conversions/ensure_sparse_matrices.py, qpsolvers/solvers/clarabel_.py, qpsolvers/solvers/highs_.py, qpsolvers/solvers/osqp_.py, qpsolvers/solvers/piqp_.py, qpsolvers/solvers/qpalm_.py, qpsolvers/solvers/scs_.py, qpsolvers/warnings.py, tests/test_solve_problem.py
This PR defines qpsolvers-related warnings, allowing them to be e.g. filtered via the standard [`warnings`](https://docs.python.org/3/library/warnings.html) module.
=> Define qpsolvers-related warnings

CHANGELOG.md, CITATION.cff, README.md, qpsolvers/__init__.py
This release adds [SIP](https://github.com/joaospinto/sip), a sparse interior point solver implemented in C++. Thanks to @joaospinto for implementing this interface 👍
Additionally, this new version adds warning filters and clears out the OSQP version pin.
- New solver: [SIP](https://github.com/joaospinto/sip_python) (thanks to @joaospinto)
- warnings: Add `SparseConversionWarning` to filter the corresponding warning
- warnings: Base class `QPWarning` for all qpsolvers-related warnings
- warnings: Recall solver name when issuing conversion warnings
- Add solver name argument to internal `ensure_sparse_matrices` function
- CICD: Update Python version to 3.10 in coverage job
- docs: Add jaxopt.OSQP to the list of supported solvers
- OSQP: Remove pre-1.0 version pin
- OSQP: Update interface …
=> Release v4.7.0

CHANGELOG.md, CITATION.cff, README.md, qpsolvers/__init__.py
This release adds support for the new API of PIQP v0.6.0, as well as macOS unit testing for KVXOPT.
Thanks to @RSchwan and @sanurielf for contributing to this release :+1: 
- PIQP: Add support for new API in v0.6.0 (thanks to @RSchwan)
- PIQP: Add new solver options to the documentation (thanks to @RSchwan)
- CICD: Enable macOS tests for KVXOPT (thanks to @sanurielf)
=> Release v4.8.0

qpsolvers/solvers/clarabel_.py
Hi Stéphane,
A small contribution from my side: clarabel currently switches to `sp.lsqr` without any warning. this PR just adds a warning for the user that clarabel is not being used.
Please let me know if any changes to the PR are needed.
=> [qpsolvers/solvers/clarabel_.py]: warn when using scipy lsqr
